# Generated by Django 5.2.4 on 2025-08-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('conductor', 'Conductor'), ('operador', 'Operador'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
