# Generated by Django 5.2.4 on 2025-09-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_rol'),
        ('partners', '0003_alter_proveedor_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='partners.cliente'),
        ),
    ]
