# Generated by Django 5.1.7 on 2025-08-21 00:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_rename_ciente_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('unidad', models.CharField(default='unidad', max_length=32)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remision', models.CharField(max_length=100)),
                ('factura', models.FileField(blank=True, help_text='PDF o imagen (png/jpg)', null=True, upload_to='cargas/facturas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('etiquetada', 'Etiquetada'), ('almacenada', 'Almacenada')], default='recibida', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='partners.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='partners.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Cargas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cargas.carga')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carga_items', to='cargas.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(db_index=True, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('despachada', 'Despachada'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carga_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='cargas.cargaitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
