# Generated by Django 5.2.4 on 2025-10-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
        ('partners', '0004_alter_proveedor_nit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carga',
            constraint=models.UniqueConstraint(fields=('cliente', 'proveedor', 'remision'), name='unique_carga_cliente_proveedor_remision'),
        ),
    ]
