# Generated by Django 5.1.7 on 2026-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_carga_unique_carga_cliente_proveedor_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='destino',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='carga',
            name='origen',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
