# Generated by Django 5.1.7 on 2026-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_carga_destino_carga_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='direccion',
            field=models.CharField(blank=True, default='Null', max_length=100, null=True),
        ),
    ]
