# Generated by Django 5.2.4 on 2025-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_rename_ciente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
