# Generated by Django 5.2.4 on 2025-09-03 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0001_initial'),
        ('partners', '0003_alter_proveedor_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(db_index=True, max_length=20, unique=True)),
                ('conductor', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('origen', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='partners.cliente')),
            ],
            options={
                'verbose_name_plural': 'Envios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='envios.envio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio_items', to='cargas.unidad')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('envio', 'unidad')},
            },
        ),
    ]
