# Generated by Django 5.2.4 on 2025-09-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_entrega_verificada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EscaneoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
                ('escaneado_por', models.CharField(blank=True, max_length=100)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envio')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.envioitem')),
            ],
            options={
                'verbose_name': 'Escaneo de Entrega',
                'verbose_name_plural': 'Escaneos de Entrega',
                'unique_together': {('envio', 'item')},
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='items_escaneados',
            field=models.ManyToManyField(blank=True, related_name='envios_escaneados', through='envios.EscaneoEntrega', to='envios.envioitem'),
        ),
    ]
