# Generated by Django 5.1.7 on 2026-02-27 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_envio_fecha_entrega_verificada_escaneoentrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envioitem',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
